### ISSUE TITLE
toJSON() not working with AnimationMaterials

### ISSUE THREAD

**Issue by SlimMarten** [zadvorsky/three.bas#30]
As far as I can tell using builtin `toJSON()` is not working.

I have a mesh using a `BAS.StandardAnimationMaterial()` and get the following error if I try to `mesh.toJSON()`:

**`Uncaught TypeError: Cannot read property 'isTexture' of null`**

**Comment by SlimMarten** [comment]
actually I just want to parse the toJSON() Object as a string to compare two instances and debug another error I am currently dealing with. Maybe the error might be related to this.

I am trying to clone the mesh to place it multiple times in my scene at different positions. But if I clone the mesh using the StandardAnimationMaterial(), somehow the shadows break. I also tried to add a new customDepthMaterial to the cloned Mesh, but without success.
Further debugging lead me to the point where I wanted to clone only a BasicAnimationMaterial and here it says:

**`Uncaught TypeError: Cannot read property 'uniformValues' of undefined`**

**Comment by zadvorsky** [comment]
I'm not used to the cloning workflow, so I've never tested it, and I'm not sure what kind of things might break because I don't implement the clone/copy methods on any of the BAS geometries and materials (they just use the method from the THREE.js class they're extending). I can look into adding clone/copy methods, but that may take some time.

If you want to create several meshes, you might be better off either creating a mesh subclass with the geometry and material (like Animation [here](https://github.com/zadvorsky/three.bas/blob/master/examples/bezier_curve/main.js), and creating instances of that, or working with a factory function.

**Comment by SlimMarten** [comment]
> I can look into adding clone/copy methods, but that may take some time.

Don't worry, thanks for all your work on this anyway, very helpful to inject built-in THREE Shaders :).

> If you want to create several meshes, you might be better off either creating a mesh subclass with the geometry and material (like Animation here, and creating instances of that, or working with a factory function.

The Subclass thing might be an option and actually is kind of close to the way I work around the problem at the moment. I simply create a new THREE.Mesh() Instance each time I used to clone instead. What do you mean by factory function?
